on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: React CI
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - run: cd client && npm install
      - run: cd client && npm test
  docker:
    runs-on: ubuntu-latest
    name: Build and push
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./client 
          tags: markadavenport/url_shortener_ex-ui:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
