on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: React CI
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - run: cd client && npm install
      - run: cd client && npm test